# Generated by Django 5.2 on 2025-05-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_edi', '0002_alter_pythontask_test_cases'),
        ('python_edi', '0002_pythontask_hints_alter_pythontask_test_cases'),
    ]

    operations = [
    ]
