version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: yolki_palki
      POSTGRES_PASSWORD: yolki_palki
      POSTGRES_DB: yolki_palki
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - default

volumes:
  postgres_data: