# Generated by Django 5.2 on 2025-05-03 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_recorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosummary',
            old_name='screenshot_name',
            new_name='segment_name',
        ),
        migrations.RenameField(
            model_name='videosummary',
            old_name='screenshot',
            new_name='video_segment',
        ),
    ]
