# Generated by Django 5.2 on 2025-05-03 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_template_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='template',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
